Feat/expand css variables
Relewise/relewise-ui-components pull request #20
Opened 2023-09-15 12:52 UTC by SWH-Relewise

2023-09-18 08:26 UTC, mzanoni requested changes
Skide godt :)

2023-09-18 08:26 UTC, mzanoni commented on packages/web-components/README.md
> +            --relewise-price-margin: 0.5rem 0rem 0rem 0rem;
Bruge disse til "salesPrice" præsentation, så burde de måske hedde `sales-price` - bare så det er tydeligt at det er den pris man styler. Og så kunne jeg godt tænke mig at alle `price` variabler lå sammen, så der ikke er `display-name` ind i mellem :)

2023-09-18 08:26 UTC, mzanoni commented on packages/web-components/src/components/product-tile.ts
> +            font-family: var(--relewise-font, Arial, Helvetica, sans-serif);
Ønske: Bruge samme default som tailwind for det er en god default. Altså:
`ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";`

2023-09-19 06:09 UTC, mzanoni commented on packages/web-components/README.md
> +            --relewise-information-container-margin: 0.5rem 0.5rem 0.5rem 0.5rem;
Jeg bemærkede ikke lige denne i første omgang. Hvad har vi i "information-container"en ?

2023-09-19 07:17 UTC, SWH-Relewise commented on packages/web-components/src/recommendations/products/product-recommendation-base.ts
> +    @property({attribute: 'displayed-at-location'})
Damn dem havde jeg glemt. 🙁

2023-09-19 07:18 UTC, SWH-Relewise commented on packages/web-components/README.md
> +            --relewise-information-container-margin: 0.5rem 0.5rem 0.5rem 0.5rem;
Det er selve kassen under billedet hvor alt information er i. 🙂

2023-09-19 09:06 UTC, mzanoni approved these changes

2023-09-19 09:06 UTC, merged